# general settings
name: vqswap
model_type: SwapperModel
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: VGGHQ
    type: VGGHQFSDataset
    dataroot_gt: 'VGGFACE 512 DATAPATH'
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 512
    gt_size: 512
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 100
    prefetch_mode: ~
    
# network structures
network_g:
  type: SwapperR1
  dim_embd: 512
  n_head: 8
  n_layers: 9
  codebook_size: 1024
  connect_list: ['16', '32', '64', '128']
  fix_modules: ['encoder','quantize','generator']
  vqgan_path: "STAGE-2—SUM-PretrainedModel" # pretrained VQGAN

network_vqgan: # this config is needed if no pre-calculated latent
  type: VQAutoEncoder
  img_size: 512
  nf: 64
  ch_mult: [1, 2, 2, 4, 4, 8]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: ProjectedDiscriminator
  diffaug: False
  interp224: False
  fix_modules: ['feature_network']

network_identity:
  type: IR100ArcFace
  block: IBasicBlock
  layers: [3, 13, 30, 3]

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: false
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~
  pretrain_network_identity: 'weights/arcface.pth'

# base_lr(4.5e-6) * bach_size(4)
train:
  autoswapping: true
  feat_loss_weight: 1.0
  scale_adaptive_gan_weight: 1.0
  use_hq_feat_loss: true
  cross_entropy_loss: true
  entropy_loss_weight: 0.1

  optim_g:
    type: Adam
    lr: !!float 7e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 2e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 2e-5 # no lr reduce in official vqgan code

  total_iter: 500000

  warmup_iter: -1  # no warm up
  ema_decay: 0.997

  use_adaptive_weight: true

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 0
  manual_seed: 0

  featmatch_opt:
    type: L1Loss
    loss_weight: 2.0

  identity_opt:
    type: CosineLoss
    loss_weight: 15.0

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: 1.0

# validation settings
val:
  val_freq: !!float 5e10 # no validation
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 99
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29413

find_unused_parameters: true

